CS3219-AY2324S1/ay2324s1-course-assessment-g42

- backend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/index.js
- frontend/src/pages/home.js
- frontend/src/pages/questions.js
- added skeleton for subpages
Home page:
- added gitignore to the backend folder
> Create subpages skeleton

- backend/controllers/user-controller.js
- backend/routes/user-route.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/navBar.js
- frontend/src/components/users/deleteUser.js
- frontend/src/components/users/editUser.js
- frontend/src/components/users/logoutUser.js
- frontend/src/pages/UserProfile.js
- frontend/src/pages/home.js
- frontend/src/pages/login.js
- frontend/src/pages/signup.js
- add error handling for errors related to login/signup etc.
- update pages related to users including user profile, login, signup
- add navbar that stays on all pages, and changes depending on if user is logged in
> update user ui and error handling

- backend/controllers/user-controller.js
- backend/middleware/auth.js
- frontend/src/components/navBar.js
- frontend/src/components/users/deleteUser.js
- frontend/src/components/users/editUser.js
- frontend/src/components/users/logoutUser.js
- frontend/src/helpers.js
- frontend/src/pages/UserProfile.js
- frontend/src/pages/login.js
- frontend/src/pages/questions.js
- frontend/src/pages/signup.js
- frontend/src/pages/viewUsers.js
- update response codes to be more consistent with SOP
- add auto logout when there is an invalid token
others:
- can clean up code if project structure allows
- can make page transitions more seamless
> add auto logout and update response codes

- README.md
- docker-compose.yml
- frontend/.dockerignore
- frontend/Dockerfile
- frontend/package.json
- nginx/Dockerfile
- nginx/default.conf
- question-service/.dockerignore
- question-service/Dockerfile
- user-service/.dockerignore
- user-service/Dockerfile
- Add docker files to question-service, user-service, frontend
- Add docker-compose.yml
- Add nginx for containers' intercommunication
Refer to README.md for instruction how to dockerize the application locally
> Assignment 4

- frontend/src/App.js
- frontend/src/components/navBar.js
- frontend/src/components/questions/formDialog.js
- frontend/src/pages/questions.js
- question-service/controllers/question-controller.js
- question-service/routes/question-route.js
Add pagination to questions page to reduce lag
- 10 questions loaded per page
> Add pagination to questions page

- .github/workflows/test.yml
- frontend/src/components/questions/formDialog.js
- frontend/src/pages/questions.js
- question-service/controllers/question-controller.js
- question-service/test/question-service-test.js
- changed duplicate title checking to backend
- added new error handling for duplicate title
- added test for duplicate title checking
> Fix duplicate title checking

- question-service/test/question-service-test.js
- user-service/controllers/user-controller.js
- user-service/test/user-service-test.js
- add tests for authentication for both user and question service
- add tests for userservice: updatepassword updateusername 
- etc.etc
> add more tests

- frontend/src/pages/match.js
- matching-service/.gitignore
- matching-service/controllers/match-controller.js
- matching-service/rpc_client.js
- matching-service/rpc_server.js
- removed hard coded matching criteria
- implemented separate queues for each matching option
> Update to flexible matching criteria

- collaboration-service/package-lock.json
- frontend/src/App.js
- frontend/src/pages/collab.js
- frontend/src/pages/match.js
- matching-service/package-lock.json
- user-service/package-lock.json
Passes room ID to collab page and uses it for socket setup
`/collab` is still kept only for UI testing purposes
- Question still not synced
- Other users can still access page (if they have the url)
> Pass roomId to collab page

- question-service/routes/question-route.js
- question-service/test/question-service-test.js
- fix getquestion api to be post instead of get
> fix getquestion api

- frontend/src/pages/signup.js
- user-service/controllers/user-controller.js
- user-service/test/user-service-test.js
> Move user related checks that do not require db to frontend

- collaboration-service/.dockerignore
- collaboration-service/Dockerfile
- docker-compose.yml
- nginx/default.conf
small PR for containerizing collaboration service with Docker
> Containerize collaboration service

- frontend/src/App.css
- frontend/src/components/navBar.js
- frontend/src/components/users/deleteUser.js
- frontend/src/components/users/editUser.js
- frontend/src/components/users/logoutUser.js
- frontend/src/pages/UserProfile.js
- update userprofile ui according to wireframe
> Update userprofile UI

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/questions/formAddCategories.js
- frontend/src/components/questions/formDialog.js
- frontend/src/components/questions/questionsFilter.js
- frontend/src/components/questions/questionsTable.js
- frontend/src/components/questions/questionsTitleFilter.js
- frontend/src/pages/questions.js
- frontend/src/styles/questions.css
- question-service/controllers/category-controller.js
- question-service/controllers/question-controller.js
- question-service/index.js
- question-service/models/categories.js
- question-service/routes/category-route.js
- add filtering by categories and complexity (filter icon next to header)
- add filtering by title (input box, search by clicking enter)
- only one filter per field (e,g, can filter for category "Array" and complexity "Easy", but not complexities "Easy" and "Medium")
> Add question filtering

- frontend/src/pages/collab.js
- move question + code to sessionstorage so it will be maintained on refresh
> bugfix: collab page blank on refresh

- frontend/src/App.js
- frontend/src/pages/collab.js
- frontend/src/styles/collab.css
Changed colours to match Figma wireframe
Closes #66
> Update collab UI

- frontend/src/App.css
- frontend/src/components/questions/formDialog.js
- frontend/src/components/questions/questionsFilter.js
- frontend/src/components/questions/questionsTable.js
- frontend/src/components/questions/questionsTitleFilter.js
- frontend/src/pages/questions.js
- frontend/src/styles/questions.css
- question-service/controllers/question-controller.js
new questions UI just dropped
- additionally fixed small bug in backend regarding regex
> Update question UI

- frontend/src/components/users/questionHistory.js
- frontend/src/pages/UserProfile.js
- frontend/src/styles/userProfile.css
Questions history service UI :0
> Add History UI

- frontend/src/pages/collab.js
- frontend/src/styles/collab.css
> add exit button to collaboration room

- frontend/src/components/users/questionHistory.js
- frontend/src/styles/userProfile.css
> Use css instead of Paper 🤮

- matching-service/package.json
- now matching-service runs on npm run dev
- this pr contains the tagged commit for assignment 5
> matching-service: Fix npm run script

- question-service/controllers/category-controller.js
- question-service/test/question-service-test.js
> Add more tests for questions and categories

- user-service/controllers/user-controller.js
- user-service/models/user-model.js
- remove interactions with db from controller and move to model to follow mvc architecture
- i live in fear that i have failed and this commit causes our whole porject to breakdown
> update users to follow mvc architecture

- chat-service/index.js
- chat-service/package.json
- frontend/src/components/collab/chatComponent.js
- fix bug due to whitespaces at the front and back of input
- fixed warnings in frontend (changed UI for showing user joined/left chat)
- chat service can now be run with npm start or npm run dev
- chat history now should be loaded correctly after refresh
> Chat service bug fixes

- frontend/src/pages/collab.js
> remove video space fr collaboration room
